on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build repo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: /root/test/dist
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: 22
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

  restart:
    name: restart webservices
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: connect to server and restart webservices | pm2 | nginx
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/test/
          pm2 kill all
          pm2 start --name backend/nest dist/main.js
          cd /root/nuxt-test/
          pm2 start ecosystem.config.cjs
